[package]
name = "wiseai"
version = "0.1.0"
authors = ["wiseaidev <oss@wiseai.dev>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.0", features = ["router", "fullstack"] }
dioxus-logger = "0.6.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
wasm-bindgen = "0.2.100"
js-sys = "0.3.77"
web-sys = { version = "0.3.77", features = ["Window", "History", "Location", "Storage", "HtmlElement", "MediaQueryList", "StorageEvent"] }
use-mdbook = { git = "https://github.com/dioxuslabs/include_mdbook", branch = "jk/build-gen" }
axum = { version = "0.7.7", optional = true }
tower-http = { version = "0.6.2", features = ["cors"], optional = true }
tokio = { version = "1.44.2", features = ["full"], optional = true }
theme = { version = "0.0.3", features = ["dio"] }
i18nrs = { version = "0.1.6", features = ["dio"] }

[features]
default = []
server = ["dioxus/server", "axum", "tower-http", "tokio"]
web = ["dioxus/web"]

[build-dependencies]
mdbook-gen = { git = "https://github.com/dioxuslabs/include_mdbook", branch = "jk/build-gen", features = ["manganis"]}
mdbook-shared = { git = "https://github.com/dioxuslabs/include_mdbook", branch = "jk/build-gen" }

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true
incremental = false

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
